### PR TITLE
Field Creation Text Length Default to 255 Bugfix

### LINKED ISSUE #923: [bug]: field creator character limit (length field) resetting to default value of 255
### Prerequisites

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've searched in the [existing issues](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues?q=is%3Aissue) and the one I'm about to create is not one of those created.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

### Describe the bug

When attempting to configure the character limit for "text" field type in you cannot easily delete the default value. If you delete the initial value of "255" it instantly repopulates. This is a minor detriment to UX as you want to set whatever value you want and instinctually one would think to delete the existing number. 

Workaround: input your new value to the left of the existing default value, then delete that value. (if you wanted the value to be "10" first move your mouse selector to the left side of the "255" value and enter "10255". Then delete the 255 for a character limit of "10". 

Happy to provide a loom link if further clarification is needed. 

### To Reproduce

1. Go to field creator (beta)
2. Add Row (by default the field type should be "Text" but if not, select field type "Text)
3. Options
4. In the "Length" field delete the value "255" (either highlight and delete or 1 character at a time). Notice the value re-populates. 

### Version

beta

### What browser are you using?

Chrome

### PR DESCRIPTION
**Pull request by DivyanshuBist**
## Describe your changes
this PR fixes [Issue 923](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/923),
we have added default value of 255

## Issue ticket number and link
[Issue 923](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/923)

## Checklist before requesting a review
- [x] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [x] Target branch is releaseCandidate and not master
- [x] I have performed a self-review of my code
- [ ] I ran the [unit tests](https://github.com/tprouvot/Salesforce-Inspector-reloaded#unit-tests) and my PR does not break any tests
- [x] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [ ] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) (optional)

### CODE REVIEW

File: addon/field-creator.js [hunk 1]
```diff
@@ -309,6 +309,19 @@ class FieldOptionModal extends React.Component {
...
+    if(name=='length' && value==""){
+        this.setState((prevState) => ({
+        field: {
+          ...prevState.field,
+          [name]: 255,
+        },
+      }));
+    }
+  };
+
```
Comment (tprouvot) [inline addon/field-creator.js]:
```suggestion
```

**Review by tprouvot — CHANGES_REQUESTED** [review]
Hi @DivyanshuBist 
Thanks for the PR

I would not prefer to use onBlur event to handle this.
Because after removing the intial value, if we click elsewhere the default value is set again and it's a kind of overkill

**Comment by tprouvot** [comment]
Thanks for the updates !

**Review by tprouvot — APPROVED** [review]
